import type { ProductWithTrader } from "./cart-context";

export const MOCK_CATEGORIES = [
  { id: "cat-1", name: "Clothing & Textiles", slug: "clothing-textiles" },
  { id: "cat-2", name: "Fresh Farm Produce", slug: "fresh-produce" },
  { id: "cat-3", name: "Coffee & Cocoa", slug: "coffee-tea" },
  { id: "cat-4", name: "Beauty & Wellness", slug: "beauty-wellness" },
  { id: "cat-5", name: "Handmade Crafts", slug: "handmade-crafts" },
  { id: "cat-6", name: "Pantry & Spices", slug: "pantry-deli" },
];

export const MOCK_TRADERS = [
  {
    id: "trader-1",
    shop_name: "Bonwire Kente Weavers",
    description: "Vibrant handwoven Kente cloth, stoles, and authentic Ghanaian textile apparel.",
    address: "Bonwire Heritage Village, Kumasi, Ashanti Region",
    status: "approved" as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user-1",
    products: [{ id: "prod-1" }, { id: "prod-12" }, { id: "prod-16" }],
  },
  {
    id: "trader-2",
    shop_name: "Makola Fresh Market & Produce",
    description: "Freshly harvested plantains, Pona yams, scotch bonnet peppers, and local spices.",
    address: "Makola Market Street, Accra, Greater Accra",
    status: "approved" as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user-2",
    products: [{ id: "prod-4" }, { id: "prod-7" }, { id: "prod-10" }, { id: "prod-13" }],
  },
  {
    id: "trader-3",
    shop_name: "Aburi Organic Shea & Soap",
    description: "Grade-A Northern Ghana shea butter, traditional Alata Samina black soap, and botanical oils.",
    address: "Aburi Botanical Gardens Road, Eastern Region",
    status: "approved" as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user-3",
    products: [{ id: "prod-2" }, { id: "prod-6" }, { id: "prod-11" }],
  },
  {
    id: "trader-4",
    shop_name: "Gold Coast Cocoa & Coffee Roasters",
    description: "Single-origin Ghanaian cocoa powder, artisanal dark chocolate, and roasted coffee beans.",
    address: "Oxford Street, Osu, Accra",
    status: "approved" as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user-4",
    products: [{ id: "prod-5" }, { id: "prod-14" }],
  },
  {
    id: "trader-5",
    shop_name: "Bolga Crafts & Woodwork",
    description: "Hand-woven elephant grass straw baskets from Bolgatanga and carved Ashanti woodwork.",
    address: "Crafts Village, Bolgatanga / Ahwiaa Market",
    status: "approved" as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user-5",
    products: [{ id: "prod-3" }, { id: "prod-8" }, { id: "prod-9" }, { id: "prod-15" }],
  },
];

export const MOCK_PRODUCTS: ProductWithTrader[] = [
  {
    id: "prod-1",
    name: "Authentic Bonwire Handwoven Kente Stole",
    description: "Vibrant traditional Ghanaian handwoven Kente cloth crafted with rich symbolic patterns by master weavers in Bonwire.",
    price: 350.00,
    stock: 15,
    image_url: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-1",
    trader_id: "trader-1",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[0],
    traders: MOCK_TRADERS[0],
  },
  {
    id: "prod-2",
    name: "Raw Organic Unrefined Shea Butter (500g Jar)",
    description: "100% natural Grade-A unrefined yellow shea butter harvested and cold-pressed by women cooperatives in Northern Ghana.",
    price: 65.00,
    stock: 40,
    image_url: "https://images.unsplash.com/photo-1608248597261-e4d990f38e68?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-4",
    trader_id: "trader-3",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[3],
    traders: MOCK_TRADERS[2],
  },
  {
    id: "prod-3",
    name: "Hand-Carved Bolgatanga Straw Market Basket",
    description: "Woven by artisan women in Bolgatanga using durable elephant grass, dyed with natural plant extracts, and finished with real leather handles.",
    price: 120.00,
    stock: 25,
    image_url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-5",
    trader_id: "trader-5",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[4],
    traders: MOCK_TRADERS[4],
  },
  {
    id: "prod-4",
    name: "Ghanaian Farm Plantain & Yam Basket (5kg)",
    description: "Freshly harvested sweet yellow plantains and premium Pona yam tubers direct from farm gates in Eastern Region.",
    price: 55.00,
    stock: 30,
    image_url: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-2",
    trader_id: "trader-2",
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[1],
    traders: MOCK_TRADERS[1],
  },
  {
    id: "prod-5",
    name: "Single-Origin Ghanaian Dark Chocolate Bars (Set of 3)",
    description: "Rich 70% dark craft chocolate bars made from ethically sourced Ghanaian cocoa beans with a smooth caramel and fruity finish.",
    price: 85.00,
    stock: 35,
    image_url: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-3",
    trader_id: "trader-4",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[2],
    traders: MOCK_TRADERS[3],
  },
  {
    id: "prod-6",
    name: "Traditional Alata Samina Black Soap Bar (250g)",
    description: "Handmade African black soap formulated with cocoa pod ash, unrefined palm kernel oil, and moisturizing shea butter.",
    price: 35.00,
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-4",
    trader_id: "trader-3",
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[3],
    traders: MOCK_TRADERS[2],
  },
  {
    id: "prod-7",
    name: "Spiced Sobolo & Hibiscus Blend (250g)",
    description: "Refreshing Ghanaian dried hibiscus flowers blended with fresh ginger, grains of selim (Hwentia), and natural spices.",
    price: 45.00,
    stock: 20,
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-6",
    trader_id: "trader-2",
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[5],
    traders: MOCK_TRADERS[1],
  },
  {
    id: "prod-8",
    name: "Hand-Carved Ashanti Fertility Doll (Akua'ba)",
    description: "Traditional wooden Akua'ba sculpture carved from sese wood by master woodworkers in Ahwiaa, Kumasi.",
    price: 180.00,
    stock: 12,
    image_url: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-5",
    trader_id: "trader-5",
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[4],
    traders: MOCK_TRADERS[4],
  },
  {
    id: "prod-9",
    name: "Hand-Woven Ghanaian Moses Basket (Baby Bassinet)",
    description: "Sustainably hand-woven baby bassinet basket made from sturdy elephant grass by master artisans in Bolgatanga.",
    price: 290.00,
    stock: 8,
    image_url: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-5",
    trader_id: "trader-5",
    created_at: new Date(Date.now() - 86400000 * 0.2).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[4],
    traders: MOCK_TRADERS[4],
  },
  {
    id: "prod-10",
    name: "Fresh Ghanaian Yellow Garri (10kg Bag)",
    description: "Fine roasted cassava granules prepared with organic red palm oil for rich aroma and golden colour.",
    price: 75.00,
    stock: 25,
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-2",
    trader_id: "trader-2",
    created_at: new Date(Date.now() - 86400000 * 0.3).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[1],
    traders: MOCK_TRADERS[1],
  },
  {
    id: "prod-11",
    name: "Artisanal Cocoa Butter Body Moisturizer (300ml)",
    description: "Deeply nourishing body cream enriched with unrefined Ghanaian cocoa butter, coconut oil, and vitamin E.",
    price: 50.00,
    stock: 30,
    image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-4",
    trader_id: "trader-3",
    created_at: new Date(Date.now() - 86400000 * 0.4).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[3],
    traders: MOCK_TRADERS[2],
  },
  {
    id: "prod-12",
    name: "Traditional Dashiki Printed Cotton Shirt",
    description: "Classic V-neck Dashiki shirt tailored with breathable 100% African cotton and bold traditional prints.",
    price: 140.00,
    stock: 18,
    image_url: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-1",
    trader_id: "trader-1",
    created_at: new Date(Date.now() - 86400000 * 0.5).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[0],
    traders: MOCK_TRADERS[0],
  },
  {
    id: "prod-13",
    name: "Ghanaian Spicy Kelewele Seasoning Mix (200g)",
    description: "Authentic spice blend of ginger, chilli, nutmeg, garlic, and cloves for making street-style fried plantains.",
    price: 25.00,
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-6",
    trader_id: "trader-2",
    created_at: new Date(Date.now() - 86400000 * 0.6).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[5],
    traders: MOCK_TRADERS[1],
  },
  {
    id: "prod-14",
    name: "Gold Coast Single-Origin Espresso Beans (500g)",
    description: "Medium-dark espresso roast with notes of cocoa nibs, toasted nuts, and wild spice notes.",
    price: 110.00,
    stock: 20,
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-3",
    trader_id: "trader-4",
    created_at: new Date(Date.now() - 86400000 * 0.7).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[2],
    traders: MOCK_TRADERS[3],
  },
  {
    id: "prod-15",
    name: "Handmade Recycled Glass Bead Necklace",
    description: "Traditional Krobo recycled glass bead necklace handcrafted using ancestral kiln-firing techniques.",
    price: 95.00,
    stock: 15,
    image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-5",
    trader_id: "trader-5",
    created_at: new Date(Date.now() - 86400000 * 0.8).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[4],
    traders: MOCK_TRADERS[4],
  },
  {
    id: "prod-16",
    name: "Hand-Printed Adinkra Pattern Table Runner",
    description: "Heavyweight cotton canvas table runner stamped with traditional Adinkra symbols of wisdom and strength.",
    price: 85.00,
    stock: 14,
    image_url: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80",
    is_active: true,
    category_id: "cat-1",
    trader_id: "trader-1",
    created_at: new Date(Date.now() - 86400000 * 0.9).toISOString(),
    updated_at: new Date().toISOString(),
    categories: MOCK_CATEGORIES[0],
    traders: MOCK_TRADERS[0],
  },
];
