/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeTraderRouteImport } from './routes/become-trader'
import { Route as CartRouteImport } from './routes/cart'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TraderRouteImport } from './routes/trader'
import { Route as TradersRouteImport } from './routes/traders'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeTraderRoute = BecomeTraderRouteImport.update({
  id: '/become-trader',
  path: '/become-trader',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TraderRoute = TraderRouteImport.update({
  id: '/trader',
  path: '/trader',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersRoute = TradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-trader': typeof BecomeTraderRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/trader': typeof TraderRoute
  '/traders': typeof TradersRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-trader': typeof BecomeTraderRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/trader': typeof TraderRoute
  '/traders': typeof TradersRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-trader': typeof BecomeTraderRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/trader': typeof TraderRoute
  '/traders': typeof TradersRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-trader'
    | '/cart'
    | '/orders'
    | '/shop'
    | '/trader'
    | '/traders'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-trader'
    | '/cart'
    | '/orders'
    | '/shop'
    | '/trader'
    | '/traders'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-trader'
    | '/cart'
    | '/orders'
    | '/shop'
    | '/trader'
    | '/traders'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeTraderRoute: typeof BecomeTraderRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  ShopRoute: typeof ShopRoute
  TraderRoute: typeof TraderRoute
  TradersRoute: typeof TradersRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-trader': {
      id: '/become-trader'
      path: '/become-trader'
      fullPath: '/become-trader'
      preLoaderRoute: typeof BecomeTraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trader': {
      id: '/trader'
      path: '/trader'
      fullPath: '/trader'
      preLoaderRoute: typeof TraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders': {
      id: '/traders'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof TradersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeTraderRoute: BecomeTraderRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  ShopRoute: ShopRoute,
  TraderRoute: TraderRoute,
  TradersRoute: TradersRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
